name: monetio-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.9
  #
  # core
  - cftime
  - dask
  - fsspec
  - netcdf4
  - numpy
  - pandas
  - requests
  - s3fs
  - xarray
  #
  # optional
  - filelock
  - h5netcdf
  - h5py
  - joblib
  - lxml
  - pyhdf !=0.11.3
  - pyresample
  - scipy
  - timezonefinder
  #
  # test
  - pytest
  - pytest-cov
  - pytest-xdist
  #
  - pip >=21.1
