name: monetio-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  #
  # core
  - dask
  - netcdf4
  - numpy
  - pandas
  - pyarrow
  - s3fs
  - scipy
  - xarray
  #
  # optional
  - filelock
  - h5netcdf
  - h5py
  - joblib
  - pyhdf!=0.11.3
  - pyproj
  - requests
  - timezonefinder
  - cubed-xarray

  #
  # virtualizarr
  - virtualizarr>=1.0
  - obstore
  - ujson
  - zarr>=3.1,<3.2
  #
  # test
  - hypothesis
  - pytest
  - pytest-xdist
  #
  - pip>=21.1
  - pip:
      - obspec_utils
      - "-e .[dev]"
