name: monetio-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python =3.11
  #
  # core
  - cftime
  - dask
  - fsspec
  - netcdf4
  - numpy
  - pandas =2.*
  - requests
  - s3fs
  - xarray
  #
  # optional
  - joblib
  #
  # docs
  - sphinx =7.*
  - sphinx-autobuild
  - sphinx_rtd_theme
  #
  - pip >=21.1
