name: CI

on:
  push:
    branches: [stable, develop]
  pull_request:
    branches: [stable, develop]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

env:
  OPENAQ_API_KEY: "${{ secrets.OPENAQ_API_KEY }}"

jobs:
  test:
    name: Test (Py ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    if: github.repository == 'noaa-oar-arl/monetio'
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python (micromamba)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment-dev.yml
          cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Test with pytest
        run: pytest -n auto --dist loadgroup -v -ra -W "ignore:Downloading test file:UserWarning::"

      - name: Test with pytspack installed
        run: |
          pip install https://github.com/noaa-oar-arl/pytspack/archive/master.zip
          pytest -k with_pytspack -n auto -v -ra -W "ignore:API key length is 0:UserWarning::"

  docs:
    name: Check docs build
    runs-on: ubuntu-latest
    if: github.repository == 'noaa-oar-arl/monetio'
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python (micromamba)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: docs/environment-docs.yml
          cache-environment: true

      - name: linkcheck
        run: sphinx-build -b linkcheck docs docs/_build/linkcheck

      - name: sphinx-build -W
        run: sphinx-build -b html -W docs docs/_build/html
