name: CI

on:
  push:
    branches: [stable, develop]
  pull_request:
    branches: [stable, develop]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  test:
    name: Test (Py ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    if: github.repository == 'noaa-oar-arl/monetio'
    strategy:
      matrix:
        python-version: ["3.6", "3.8", "3.10"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (micromamba) [>3.6]
        if: matrix.python-version != '3.6'
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Set up Python (micromamba) [3.6]
        if: matrix.python-version == '3.6'
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}
            attrs=22.2.0

      - name: Test with pytest
        run: pytest -n auto -v

      - name: Test with pytspack installed
        run: |
          pip install https://github.com/noaa-oar-arl/pytspack/archive/master.zip
          pytest -n auto -v -k with_pytspack

  docs:
    name: Check docs build
    runs-on: ubuntu-latest
    if: github.repository == 'noaa-oar-arl/monetio'
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (micromamba)
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: docs/environment-docs.yml
          cache-environment: true

      - name: linkcheck
        run: sphinx-build -b linkcheck docs docs/_build/linkcheck

      - name: sphinx-build -W
        run: sphinx-build -b html -W docs docs/_build/html
